allowBuilds:
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - '@rolldown/binding-darwin-arm64@1.2.6'
  - '@rolldown/binding-freebsd-x64@1.2.6'
  - '@rolldown/binding-linux-s390x-gnu@1.2.6'
  - '@rolldown/binding-linux-x64-musl@1.2.6'
  - '@rolldown/binding-openharmony-arm64@1.2.6'
